// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFH2Hk5-2Xy6QU4jsemNi778B26geJFOw',
    appId: '1:270202455719:web:997b5f54f2d24a1d6bbd82',
    messagingSenderId: '270202455719',
    projectId: 'vstock-207cf',
    authDomain: 'vstock-207cf.firebaseapp.com',
    storageBucket: 'vstock-207cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-S6mo4nMO-9-Z0dFGbibPnmjNWfXxGoc',
    appId: '1:270202455719:android:44a17da84dbf60be6bbd82',
    messagingSenderId: '270202455719',
    projectId: 'vstock-207cf',
    storageBucket: 'vstock-207cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFlyr3FIJPyQrtmpaA3fMui3cUgtBxU9k',
    appId: '1:270202455719:ios:d5027a5f826d59356bbd82',
    messagingSenderId: '270202455719',
    projectId: 'vstock-207cf',
    storageBucket: 'vstock-207cf.appspot.com',
    androidClientId: '270202455719-njs2p9ggeehs85hku1pqam643jcnl8r4.apps.googleusercontent.com',
    iosClientId: '270202455719-ubbpbo8lsvm5sid52foau6ff12ssq21t.apps.googleusercontent.com',
    iosBundleId: 'com.example.vstock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFlyr3FIJPyQrtmpaA3fMui3cUgtBxU9k',
    appId: '1:270202455719:ios:8150dd06b4be260c6bbd82',
    messagingSenderId: '270202455719',
    projectId: 'vstock-207cf',
    storageBucket: 'vstock-207cf.appspot.com',
    androidClientId: '270202455719-njs2p9ggeehs85hku1pqam643jcnl8r4.apps.googleusercontent.com',
    iosClientId: '270202455719-4mdlm9e0g75q5endenqt9h07tp1l2tk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.vstock.RunnerTests',
  );
}
